### ISSUE TITLE
RC npm: CLI instructions are confusing

### ISSUE THREAD

**Issue by ljharb** [ossf/package-manager-best-practices#12]
> If you need to run a CLI package tool-cli from the registry:

Most projects will already have a `package.json`, so the advice should be to install the CLI tool in your project, and then run it via `npx` or inside an `npm run-script`. `package.json` isn't referred to as a "wrapper" manifest file anywhere; it _is_ a manifest file, but nobody in the npm ecosystem calls it that - it's just package.json.

**Comment by lirantal** [comment]
Agree and will add that maybe we should add an explicit note to discourage users from installing CLI tools globally, unless they indeed intend to use them as such (as opposed to using it for a specific project).

**Comment by laurentsimon** [comment]
This was addressed in https://github.com/ossf/package-manager-best-practices/pull/22. Closing.
Please re-open if needed.
