### ISSUE TITLE
RC npm: do not recommend publishing from CI

### ISSUE THREAD

**Issue by ljharb** [ossf/package-manager-best-practices#13]
Automation publish tokens are explicitly one-factor, which imo is _less_ secure than publishing directly from a dev's laptop.

If npm supported [staged builds](https://github.com/npm/rfcs/pull/92), then publishing a staged build from CI, and then a human using 2FA locally to "promote" it, would be the most secure way to publish - but lacking that, the best I think we can get is using CI to generate a tagged release commit, and then having a publisher locally download it, run `npm install` or `npm ci`, and `npm publish`.

**Comment by jeffmendoza** [comment]
Closed with #27
