### ISSUE TITLE
RC npm: incorrect claim about `colors`

### ISSUE THREAD

**Issue by ljharb** [ossf/package-manager-best-practices#7]
The issue with the `color` package wasn't that the installation wasn't reproducible; it was: anyone can check the immutable contents of any npm package on https://unpkg.com, and it's only _install scripts_ that can make a package installation not deterministically reproducible. The issue with `colors` was that there was malicious code in the package; whether that code was in the single-maintainer-owned repo or not was irrelevant (except that it may have _slightly_ delayed discovery).

Something that's entirely distinct is whether you can get between the source code (which may not even exist publicly) and the published package (which is immutable), but that's a kind of reproducibility that's more about "can someone else replicate the process that led to the package tarball" - and it has nothing to do with installation.

**Comment by jeffmendoza** [comment]
By "Reproducable Installation" we mean the consumption of packages. By this we are saying that without one of the two methods described further down in the section (vendoring or pinning/lock file), it is possible to get different results each time you npm-install your own package (by getting a new version). The colors example is to show that without vendoring or pinning, you would automatically get the new compromised version.

This is the first line:
>  A reproducible installation is one that guarantees the exact same copy the dependencies are used each time the package is installed.

Any suggestions on how to clarify what we mean here?

The install scripts situation is another worry, lets figure out where/how to add that to the doc as well. (#15)

**Comment by ljharb** [comment]
That's a potential issue with every package - you can get a new bug every time you `npm install` also. Malice (ie, `colors` or similar incidents) is irrelevant and not required to demonstrate the need for applications to have lockfiles.
