### ISSUE TITLE
RC npm: vendoring dependencies is a horrifically bad practice we should be actively discouraging

### ISSUE THREAD

**Issue by ljharb** [ossf/package-manager-best-practices#8]
Vendoring dependencies inflates repo size, costs DX, and doesn't add security - imo it makes it worse, because malicious code can be hiding inside the repo, and developers may think they don't need to audit the code because it's already in the repo.

It's not any easier to audit dependency code by having it be vendored, since all that code can be trivially retrieved with `npm install` for auditing purposes.

We should be actively discouraging vendoring - not simply describing it neutrally.

**Comment by jeffmendoza** [comment]
I agree that vendoring tends to encourage bad practices. We probably don't want to recommend it, and even discourage it, as you say.

We do want to be careful and not say that vendoring cannot be secure. It can be done securely, and we don't want to tell those people that they are wrong for vendoring.

Wording for a better warning here for that section appreciated.

**Comment by ljharb** [comment]
That's kind of like saying that rolling your own encryption/authentication can be secure.

It's indeed _technically_ true, but in practice, the likelihood asymptotically approaches zero.
